apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/os.linux: supported
  name: clair.v0.1.0
spec:
  customresourcedefinitions:
    owned:
    - description: Resource describing a Clair system.
      displayName: Clair
      kind: Clair
      name: clairs.clairproject.org
      resources:
      - kind: ConfigMap
        version: v1
      - kind: Secret
        version: v1
      - kind: Ingress
        version: networking.k8s.io/v1
      - kind: Indexer
        name: indexers
        version: clairproject.org/v1alpha1
      - kind: Matcher
        name: matchers
        version: clairproject.org/v1alpha1
      - kind: Notifier
        name: notifiers
        version: clairproject.org/v1alpha1
      - kind: Updater
        name: updaters
        version: clairproject.org/v1alpha1
      specDescriptors:
      - description: ""
        displayName: ""
        path: databases.indexer
        x-descriptors: []
      - description: ""
        displayName: Indexer database Secret name
        path: databases.indexer.name
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: ""
        displayName: Indexer database Secret key
        path: databases.indexer.key
        x-descriptors:
        - urn:alm:descriptor:com:tectonic.ui:text
      - description: ""
        displayName: ""
        path: databases.matcher
        x-descriptors: []
      - description: ""
        displayName: Matcher database Secret name
        path: databases.matcher.name
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: ""
        displayName: Matcher database Secret key
        path: databases.matcher.key
        x-descriptors:
        - urn:alm:descriptor:com:tectonic.ui:text
      - description: ""
        displayName: ""
        path: databases.notifier
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:notifier:true
      - description: ""
        displayName: Notifier database Secret name
        path: databases.notifier.name
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: ""
        displayName: Notifier database Secret key
        path: databases.notifier.key
        x-descriptors:
        - urn:alm:descriptor:com:tectonic.ui:text
      - description: Configuration dropins
        displayName: Dropins
        path: dropins
        x-descriptors: []
      - description: ""
        displayName: Name of referent
        path: dropins[0].configMapKeyRef.name
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:ConfigMap
      - description: ""
        displayName: ""
        path: dropins[0].configMapKeyRef.key
        x-descriptors:
        - urn:alm:descriptor:com:tectonic.ui:text
      - description: ""
        displayName: Name of referent
        path: dropins[0].secretKeyRef.name
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: ""
        displayName: ""
        path: dropins[0].secretKeyRef.key
        x-descriptors:
        - urn:alm:descriptor:com:tectonic.ui:text
      - description: The container image to use for Deployments
        displayName: Clair container image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com:tectonic.ui:text
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Enable the Notifier component.
        displayName: Notifier
        path: notifier
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors: []
      version: v1alpha1
    - description: Resource describing an Indexer component.
      displayName: Indexer
      kind: Indexer
      name: indexers.clairproject.org
      resources:
      - kind: ConfigMap
        version: v1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      - kind: Deployment
        version: apps/v1
      - kind: HorizontalPodAutoscaler
        version: autoscaling/v2
      specDescriptors: []
      statusDescriptors: []
      version: v1alpha1
    - description: Resource describing a Matcher component.
      displayName: Matcher
      kind: Matcher
      name: matchers.clairproject.org
      resources:
      - kind: ConfigMap
        version: v1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      - kind: Deployment
        version: apps/v1
      - kind: HorizontalPodAutoscaler
        version: autoscaling/v2
      specDescriptors: []
      statusDescriptors: []
      version: v1alpha1
    - description: Resource describing a Notifier component.
      displayName: Notifier
      kind: Notifier
      name: notifiers.clairproject.org
      resources:
      - kind: ConfigMap
        version: v1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      - kind: Deployment
        version: apps/v1
      - kind: HorizontalPodAutoscaler
        version: autoscaling/v2
      specDescriptors: []
      statusDescriptors: []
      version: v1alpha1
    - description: Resource describing an Updater component.
      displayName: Updater
      kind: Updater
      name: updaters.clairproject.org
      resources:
      - kind: ConfigMap
        version: v1
      - kind: Secret
        version: v1
      - kind: Service
        version: v1
      - kind: CronJob
        version: batch/v1
      specDescriptors: []
      statusDescriptors: []
      version: v1alpha1
    required:
    - kind: Gateway
      name: gateways.gateway.networking.k8s.io
      version: v1
    - kind: HTTPRoute
      name: gateways.gateway.networking.k8s.io
      version: v1
    - kind: GRPCRoute
      name: gateways.gateway.networking.k8s.io
      version: v1
  description: This is an operator for Clair.
  displayName: Clair Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgaWQ9IkxheWVyXzEiCiAgIGhlaWdodD0iMTAyNCIKICAgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIKICAgd2lkdGg9IjEwMjQiCiAgIHZlcnNpb249IjEuMSIKICAgc29kaXBvZGk6ZG9jbmFtZT0iaWNvbi5zdmciCiAgIGlua3NjYXBlOnZlcnNpb249IjEuMi4yIChiMGE4NDg2NTQxLCAyMDIyLTEyLTAxKSIKICAgeG1sbnM6aW5rc2NhcGU9Imh0dHA6Ly93d3cuaW5rc2NhcGUub3JnL25hbWVzcGFjZXMvaW5rc2NhcGUiCiAgIHhtbG5zOnNvZGlwb2RpPSJodHRwOi8vc29kaXBvZGkuc291cmNlZm9yZ2UubmV0L0RURC9zb2RpcG9kaS0wLmR0ZCIKICAgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIgogICB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8ZGVmcwogICAgIGlkPSJkZWZzNjYiIC8+CiAgPHNvZGlwb2RpOm5hbWVkdmlldwogICAgIGlkPSJuYW1lZHZpZXc2NCIKICAgICBwYWdlY29sb3I9IiM1MDUwNTAiCiAgICAgYm9yZGVyY29sb3I9IiNmZmZmZmYiCiAgICAgYm9yZGVyb3BhY2l0eT0iMSIKICAgICBpbmtzY2FwZTpzaG93cGFnZXNoYWRvdz0iMCIKICAgICBpbmtzY2FwZTpwYWdlb3BhY2l0eT0iMCIKICAgICBpbmtzY2FwZTpwYWdlY2hlY2tlcmJvYXJkPSIxIgogICAgIGlua3NjYXBlOmRlc2tjb2xvcj0iIzUwNTA1MCIKICAgICBzaG93Z3JpZD0iZmFsc2UiCiAgICAgaW5rc2NhcGU6em9vbT0iMS4wNDA4IgogICAgIGlua3NjYXBlOmN4PSI2ODMuMTI4MzYiCiAgICAgaW5rc2NhcGU6Y3k9IjUwOS4yMjM2NyIKICAgICBpbmtzY2FwZTp3aW5kb3ctd2lkdGg9IjI1NjAiCiAgICAgaW5rc2NhcGU6d2luZG93LWhlaWdodD0iMTQwMyIKICAgICBpbmtzY2FwZTp3aW5kb3cteD0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3cteT0iMCIKICAgICBpbmtzY2FwZTp3aW5kb3ctbWF4aW1pemVkPSIxIgogICAgIGlua3NjYXBlOmN1cnJlbnQtbGF5ZXI9IkxheWVyXzEiIC8+CiAgPHN0eWxlCiAgICAgaWQ9InN0eWxlNTEiPi5zdDB7ZmlsbDojNTZhM2Q5fS5zdDF7ZmlsbDojZjE2MjZlfTwvc3R5bGU+CiAgPGcKICAgICBpZD0iZzYxIgogICAgIHRyYW5zZm9ybT0ibWF0cml4KDkuMjc0MjU3MywwLDAsOS4yNzQyNTczLDMyLjA3OTY5NywtNjkuOTM1NjExKSI+CiAgICA8cGF0aAogICAgICAgY2xhc3M9InN0MCIKICAgICAgIGQ9Ik0gNTIuNCwxMS4xIEMgMjMuOSwxMC43IDAuNCwzMy41IDAsNjIgYyAtMC40LDI4LjUgMjIuNCw1MiA1MSw1Mi40IGggNDIuOSBjIDYuMywwIDkuNiwtMy4yIDkuNiwtOS4xIFYgNjMuMSBDIDEwMy42LDM0LjggODAuOSwxMS41IDUyLjQsMTEuMSBaIE0gNTEsMTAyLjQgQyAyOS4yLDEwMi4xIDExLjgsODQuMiAxMi4xLDYyLjQgMTIuNCw0MC42IDMwLjMsMjMuMiA1Mi4xLDIzLjUgNzMuOSwyMy44IDkxLjMsNDEuNyA5MSw2My41IDkwLjcsODUuMyA3Mi44LDEwMi43IDUxLDEwMi40IFoiCiAgICAgICBpZD0icGF0aDU1IiAvPgogICAgPHBhdGgKICAgICAgIGNsYXNzPSJzdDAiCiAgICAgICBkPSJNIDM3LjcsNTYuMyBDIDM5LDUzLjUgNDEuMiw1MS4xIDQ0LjEsNDkuNSA0Ni45LDQ4IDUwLDQ3LjQgNTIuOSw0Ny43IEwgNTcuMSwzMi4zIEMgNTAuMywzMS4xIDQzLDMyIDM2LjUsMzUuNyAyOS43LDM5LjUgMjQuOSw0NS40IDIyLjQsNTIuMSBaIG0gNy4yLDIwLjYgQyA0Mi4xLDc1LjYgMzkuNiw3My40IDM4LDcwLjUgMzYuNSw2Ny43IDM1LjksNjQuNiAzNi4yLDYxLjcgTCAyMC44LDU3LjUgYyAtMS4zLDYuOCAtMC4zLDE0LjEgMy40LDIwLjcgMy44LDYuNyA5LjgsMTEuNSAxNi41LDE0IHoiCiAgICAgICBpZD0icGF0aDU3IiAvPgogICAgPHBhdGgKICAgICAgIGNsYXNzPSJzdDEiCiAgICAgICBkPSJtIDY1LjQsNjkuNiBjIC0xLjMsMi44IC0zLjUsNS4zIC02LjQsNi45IC0yLjgsMS41IC01LjgsMi4xIC04LjcsMS44IEwgNDYsOTMuNyBjIDYuOCwxLjIgMTQuMSwwLjIgMjAuNiwtMy40IDYuOCwtMy44IDExLjYsLTkuNyAxNC4xLC0xNi41IHoiCiAgICAgICBpZD0icGF0aDU5IiAvPgogIDwvZz4KPC9zdmc+Cg==
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions: []
      deployments:
      - name: clair-operator
      permissions:
      - serviceAccountName: clair-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - clair
  - security
  links:
  - name: Source Code
    url: https://github.com/quay/clair-operator
  maintainers:
  - name: The Clair Authors
    url: https://clairproject.org/
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
  - name: The Clair Authors
    url: https://clairproject.org/
  version: 0.1.0
  webhookdefinitions: []
